baseURL = "https://brycev.com"
languageCode = "en-us"
title = "Bryce Vandegrift's Website"

[outputs]
	home = ["HTML", "RSS"]
	section = ["HTML"]
	taxonomy = ["HTML"]


[outputFormats]
	[outputFormats.RSS]
	mediatype = "application/rss"
	baseName = "rss"
